### ISSUE TITLE
confusing code mapping from ExtStatusCode to Error::Execution or Error::Unknown

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/mantle#129]
https://github.com/oasislabs/mantle/blob/5c43d3b30182b203aef237b0386f28d94019f887/mantle/src/backend/ext.rs#L60

```
impl From<ExtStatusCode> for Error {
    fn from(code: ExtStatusCode) -> Self {
        match code {
            ExtStatusCode::InsufficientFunds => Error::InsufficientFunds,
            ExtStatusCode::InvalidInput => Error::InvalidInput,
            ExtStatusCode::NoAccount => Error::NoAccount,
            code if code.0 < u32::from(u8::max_value()) => Error::Unknown,
            code => Error::Execution {
                code: code.0,
                payload: fetch_err(),
            },
        }
    }
}
```
why `code.0 < u32::from(u8::max_value())` and not `<=`?  Why are values 0-254 (but not 255) mapped to Error::Unknown?  Are the non-exhaustive enumeration for `ExtStatusCode` from
https://github.com/oasislabs/mantle/blob/master/mantle-types/src/lib.rs#L59
supposed to have an explanation for values below 255 are reserved?  Is this code trying to (sort of) map to https://github.com/oasislabs/mantle/blob/master/mantle/src/error.rs but `Error::Execution` code should never have values in 0-254?  or if those are allowed, they will never be created from `Error` via this interface?  If 0-3 for `ExtStatusCode` are used, then 4-254 are mapped to `Error::Unknown`.

the lack of comments or other hints make understanding why the code might be written this way and especially if it might not be correct difficult, since the what the actual goal is is unclear.

**Comment by bennetyee** [comment]
Addendum: `ExtStatusCode::Success` is mapped to `Error::Unknown` which is probably undesirable/will be confusing when it happens, unless it's guaranteed that all users of this code will never convert `ExtStatusCode` to `Error` when the `ExtStatusCode` is `Success`.  Even so, it might be better to handle it, because it's impossible to enforce such a guarantee.

**Comment by nhynes** [comment]
The idea here was to have 256 reserved error codes and have the remainder be user defined. It's not documented anywhere because this interface isn't fully baked. The `ext` backend is used for testing, but as you'll notice, [the testing backend is rather incomplete](https://github.com/oasislabs/mantle/blob/master/mantle-test/src/ext.rs). It hasn't been a high priority since I'll likely have to rewrite it anyway (especially since I realized that passing WASI status codes back to the caller was going to be much more challenging than just sending an application-defined error payload to stderr). This code won't be deployed on-chain, so it's not particularly unsafe. I'll p2 this issue for now, but I'll leave it open as a reminder when I get to the testing framework.

>  it's impossible to enforce such a guarantee

Perhaps in general, but [not in this codebase](https://github.com/oasislabs/mantle/blob/master/mantle/src/backend/ext.rs#L72-L73). I'll add a panic just in case, so that people catch it during testing. [Rust will eventually get dispatch on subtypes, so maybe eventually, after all!](https://github.com/rust-lang/rust/issues/44580).
